# Generated by Django 3.0.3 on 2020-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200225_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
