# Generated by Django 3.0.3 on 2020-07-11 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200302_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ScanInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='curator',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, default='null', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='original',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='language',
            name='translatedIn',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter e brief description of the book', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publishHouse',
            field=models.ManyToManyField(to='catalog.PublishHouse'),
        ),
    ]
