# Generated by Django 3.0.3 on 2020-07-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200712_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers_img',
            field=models.ImageField(default='static/img/defaultCoversImg.png', upload_to='covers'),
        ),
    ]
