# Generated by Django 3.0.3 on 2020-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_covers_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='translatedIn',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
    ]
