# Generated by Django 3.0.3 on 2020-07-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200712_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Language'),
        ),
    ]
