# Generated by Django 3.0.3 on 2020-07-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200712_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translate', to='catalog.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='catalog.Author'),
        ),
    ]
