# Generated by Django 3.0.3 on 2020-07-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200712_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author', to='catalog.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='translate',
        ),
        migrations.AddField(
            model_name='book',
            name='translate',
            field=models.ManyToManyField(related_name='translate', to='catalog.Author'),
        ),
    ]
