# Generated by Django 3.0.3 on 2020-07-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200712_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, default='null', related_name='author', to='catalog.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='curator',
        ),
        migrations.AddField(
            model_name='book',
            name='curator',
            field=models.ManyToManyField(blank=True, null=True, related_name='curator', to='catalog.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translate',
            field=models.ManyToManyField(blank=True, default='null', related_name='translate', to='catalog.Author'),
        ),
    ]
