# Generated by Django 3.0.3 on 2020-07-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200712_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this book.', null=True, to='catalog.Genre'),
        ),
    ]
