# Generated by Django 3.0.3 on 2020-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200712_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='covers_img',
            field=models.ImageField(default='static/img/covers/defaultCoversImg.png', upload_to='static/img/covers'),
        ),
    ]
