# Generated by Django 3.0.3 on 2020-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200712_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='covers_img',
            field=models.ImageField(default='img/covers/defaultCoversImg.png', upload_to='img/covers'),
        ),
    ]
